module.exports = class Data1747396363462 {
    name = 'Data1747396363462'

    async up(db) {
        await db.query(`CREATE TABLE "amm_configs" ("id" character varying NOT NULL, "bump" integer NOT NULL, "index" integer NOT NULL, "owner" text NOT NULL, "protocol_fee_rate" integer NOT NULL, "trade_fee_rate" integer NOT NULL, "tick_spacing" integer NOT NULL, "fund_fee_rate" integer NOT NULL, "fund_owner" text NOT NULL, CONSTRAINT "PK_6e011a3f9bf15be8931a3b9e7cb" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "pool_manager" ("id" character varying NOT NULL, "pool_count" integer NOT NULL, "swap_count" numeric NOT NULL, "total_volume_usd" numeric NOT NULL, "total_fees_usd" numeric NOT NULL, "pool_manager_address" text NOT NULL, "chain_id" integer NOT NULL, CONSTRAINT "PK_022054ff3c7f8000db679b0e953" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "bundle" ("id" character varying NOT NULL, "native_price_usd" numeric NOT NULL, "chain_id" integer NOT NULL, CONSTRAINT "PK_637e3f87e837d6532109c198dea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "token_day_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "token_id" character varying NOT NULL, "swap_count" numeric NOT NULL, "open" numeric NOT NULL, "high" numeric NOT NULL, "low" numeric NOT NULL, "close" numeric NOT NULL, "chain_id" integer NOT NULL, CONSTRAINT "PK_73fc06337215e86196b36822116" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_b8950a8bc7b60231137573740e" ON "token_day_data" ("token_id") `)
        await db.query(`CREATE TABLE "token_hour_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "token_id" character varying NOT NULL, "swap_count" numeric NOT NULL, "open" numeric NOT NULL, "high" numeric NOT NULL, "low" numeric NOT NULL, "close" numeric NOT NULL, "chain_id" integer NOT NULL, CONSTRAINT "PK_c05e57412a0166a5b8558d6e796" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7080974648c0d2c3baceb239c4" ON "token_hour_data" ("token_id") `)
        await db.query(`CREATE TABLE "token" ("id" character varying NOT NULL, "name" text NOT NULL, "symbol" text NOT NULL, "decimals" integer NOT NULL, "price" numeric NOT NULL, "pool_count" integer NOT NULL, "swap_count" numeric NOT NULL, "chain_id" integer NOT NULL, "token_address" text NOT NULL, "block_number" numeric NOT NULL, "timestamp" numeric NOT NULL, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "manager" ("id" character varying NOT NULL, "manager_address" text NOT NULL, "chain_id" integer NOT NULL, CONSTRAINT "PK_b3ac840005ee4ed76a7f1c51d01" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "hook" ("id" character varying NOT NULL, "is_whitelisted" boolean NOT NULL, "is_blacklisted" boolean NOT NULL, "chain_id" integer NOT NULL, "hook_address" text NOT NULL, "block_number" numeric NOT NULL, "timestamp" numeric NOT NULL, CONSTRAINT "PK_4fae52db3090a56452a9c93e0ed" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "pool_day_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "liquidity" numeric NOT NULL, "sqrt_price" numeric NOT NULL, "tick" integer NOT NULL, "volume_token0" numeric NOT NULL, "volume_token0_d" text NOT NULL, "volume_token1" numeric NOT NULL, "volume_token1_d" text NOT NULL, "volume_usd" numeric NOT NULL, "volume_percentage_change" numeric NOT NULL, "collected_fees_token0" numeric NOT NULL, "collected_fees_token1" numeric NOT NULL, "collected_fees_usd" numeric NOT NULL, "swap_count" numeric NOT NULL, "open" numeric NOT NULL, "high" numeric NOT NULL, "low" numeric NOT NULL, "close" numeric NOT NULL, "chain_id" integer NOT NULL, CONSTRAINT "PK_712b106eb8cc6842af6ca4cab80" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2f4c9e466537cf8101cbdceaea" ON "pool_day_data" ("pool_id") `)
        await db.query(`CREATE TABLE "pool_hour_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "liquidity" numeric NOT NULL, "sqrt_price" numeric NOT NULL, "tick" integer NOT NULL, "volume_token0" numeric NOT NULL, "volume_token0_d" text NOT NULL, "volume_token1" numeric NOT NULL, "volume_token1_d" text NOT NULL, "volume_usd" numeric NOT NULL, "volume_percentage_change" numeric NOT NULL, "collected_fees_token0" numeric NOT NULL, "collected_fees_token1" numeric NOT NULL, "collected_fees_usd" numeric NOT NULL, "swap_count" numeric NOT NULL, "open" numeric NOT NULL, "high" numeric NOT NULL, "low" numeric NOT NULL, "close" numeric NOT NULL, "chain_id" integer NOT NULL, CONSTRAINT "PK_bd3e248a4a44a474ee2710ec329" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_45e83e45011ed1000559b91726" ON "pool_hour_data" ("pool_id") `)
        await db.query(`CREATE TABLE "pool" ("id" character varying NOT NULL, "token0_id" character varying NOT NULL, "token1_id" character varying NOT NULL, "token0_decimals" integer NOT NULL, "token1_decimals" integer NOT NULL, "amount0" numeric NOT NULL, "amount0_d" text NOT NULL, "amount1" numeric NOT NULL, "amount1_d" text NOT NULL, "price0" numeric NOT NULL, "price1" numeric NOT NULL, "pool_address" text NOT NULL, "fee" integer NOT NULL, "hook_id" character varying NOT NULL, "sqrt_price_x96" numeric NOT NULL, "current_tick" integer NOT NULL, "liquidity" numeric NOT NULL, "volume_token0" numeric NOT NULL, "volume_token0_d" text NOT NULL, "volume_token1" numeric NOT NULL, "volume_token1_d" text NOT NULL, "volume_usd" numeric NOT NULL, "collected_fees_token0" numeric NOT NULL, "collected_fees_token1" numeric NOT NULL, "collected_fees_usd" numeric NOT NULL, "tvl_usd" numeric NOT NULL, "tick_spacing" integer NOT NULL, "batch_block_minimum_tick" integer NOT NULL, "batch_block_maximum_tick" integer NOT NULL, "swap_count" numeric NOT NULL, "chain_id" integer NOT NULL, "block_number" numeric NOT NULL, "timestamp" numeric NOT NULL, "created_at_timestamp" numeric NOT NULL, "created_at_block_number" numeric NOT NULL, CONSTRAINT "PK_db1bfe411e1516c01120b85f8fe" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_338531367ed63e3eb8e1939980" ON "pool" ("token0_id") `)
        await db.query(`CREATE INDEX "IDX_479321eabdd500587fddd0ee88" ON "pool" ("token1_id") `)
        await db.query(`CREATE INDEX "IDX_0c748715160c52dcab5bb3492d" ON "pool" ("hook_id") `)
        await db.query(`CREATE TABLE "position" ("id" character varying NOT NULL, "nft_id" numeric NOT NULL, "lower_tick" integer NOT NULL, "upper_tick" integer NOT NULL, "liquidity" numeric NOT NULL, "amount0" numeric NOT NULL, "amount0_d" text NOT NULL, "amount1" numeric NOT NULL, "amount1_d" text NOT NULL, "token0_id" character varying, "token1_id" character varying, "core_total_usd" numeric NOT NULL, "manager_id" character varying NOT NULL, "pool_id" character varying, "owner_id" character varying NOT NULL, "ratio" numeric NOT NULL, "chain_id" integer NOT NULL, "block_number" numeric NOT NULL, "timestamp" numeric NOT NULL, CONSTRAINT "PK_b7f483581562b4dc62ae1a5b7e2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f230b92ea5e4bdf8bd6658c629" ON "position" ("token0_id") `)
        await db.query(`CREATE INDEX "IDX_32d393d9b4c15d1f3253445453" ON "position" ("token1_id") `)
        await db.query(`CREATE INDEX "IDX_59d4badb979f73316f8e0a08a0" ON "position" ("manager_id") `)
        await db.query(`CREATE INDEX "IDX_128820371117dcf3915dc01ad3" ON "position" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_8134902075edc5e996ec0d7172" ON "position" ("owner_id") `)
        await db.query(`CREATE TABLE "wallet" ("id" character varying NOT NULL, "wallet_address" text NOT NULL, "chain_id" integer NOT NULL, CONSTRAINT "PK_bec464dd8d54c39c54fd32e2334" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "modify_liquidity_reccord" ("id" character varying NOT NULL, "pool_id" text NOT NULL, "pool_entity_id" character varying NOT NULL, "liquidity_delta" numeric NOT NULL, "salt" text NOT NULL, "sender_id" character varying NOT NULL, "tick_lower" integer NOT NULL, "tick_upper" integer NOT NULL, "hash" text NOT NULL, "tx_at_timestamp" numeric NOT NULL, "tx_at_block_number" numeric NOT NULL, CONSTRAINT "PK_139143ac27ef5863c1a609da623" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_430b2f79d98293631022471a10" ON "modify_liquidity_reccord" ("pool_entity_id") `)
        await db.query(`CREATE INDEX "IDX_3b5836dd8b218113f7c7fb0527" ON "modify_liquidity_reccord" ("sender_id") `)
        await db.query(`CREATE TABLE "swap_reccord" ("id" character varying NOT NULL, "pool_id" text NOT NULL, "pool_entity_id" character varying NOT NULL, "amount0" numeric NOT NULL, "amount1" numeric NOT NULL, "fee" integer NOT NULL, "liquidity" numeric NOT NULL, "sender_id" character varying NOT NULL, "sqrt_price_x96" numeric NOT NULL, "tick" integer NOT NULL, "hash" text NOT NULL, "tx_at_timestamp" numeric NOT NULL, "tx_at_block_number" numeric NOT NULL, CONSTRAINT "PK_0fae7aefb05911d3c26d3d91123" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1ee134afb92be9c3fc2b5fe9d6" ON "swap_reccord" ("pool_entity_id") `)
        await db.query(`CREATE INDEX "IDX_7a658a5896b4bca4b097a4d456" ON "swap_reccord" ("sender_id") `)
        await db.query(`CREATE TABLE "donate_reccord" ("id" character varying NOT NULL, "pool_id" text NOT NULL, "pool_entity_id" character varying NOT NULL, "amount0" numeric NOT NULL, "amount1" numeric NOT NULL, "sender_id" character varying NOT NULL, "hash" text NOT NULL, "tx_at_timestamp" numeric NOT NULL, "tx_at_block_number" numeric NOT NULL, CONSTRAINT "PK_3f98f4f7019cdb1732d34394815" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_292b419e04b723d968e150efc2" ON "donate_reccord" ("pool_entity_id") `)
        await db.query(`CREATE INDEX "IDX_1f36445a77d0839636ad31fd68" ON "donate_reccord" ("sender_id") `)
        await db.query(`CREATE TABLE "pair_records" ("id" character varying NOT NULL, "pool_id" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "token0" text NOT NULL, "token0_decimals" integer NOT NULL, "token1" text NOT NULL, "token1_decimals" integer NOT NULL, "base_stable" boolean NOT NULL, "sqrt_price_x64" numeric NOT NULL, CONSTRAINT "PK_9ff6f44aadf62b6a89c93acf4d2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_748e6851d2065409a0b2d263ae" ON "pair_records" ("token0") `)
        await db.query(`CREATE INDEX "IDX_82f0466ecec760560880a1e5a9" ON "pair_records" ("token1") `)
        await db.query(`ALTER TABLE "token_day_data" ADD CONSTRAINT "FK_b8950a8bc7b60231137573740ea" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "token_hour_data" ADD CONSTRAINT "FK_7080974648c0d2c3baceb239c4e" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_day_data" ADD CONSTRAINT "FK_2f4c9e466537cf8101cbdceaea1" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_hour_data" ADD CONSTRAINT "FK_45e83e45011ed1000559b91726f" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_338531367ed63e3eb8e1939980f" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_479321eabdd500587fddd0ee88b" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_0c748715160c52dcab5bb3492d6" FOREIGN KEY ("hook_id") REFERENCES "hook"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_f230b92ea5e4bdf8bd6658c6292" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_32d393d9b4c15d1f3253445453e" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_59d4badb979f73316f8e0a08a02" FOREIGN KEY ("manager_id") REFERENCES "manager"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_128820371117dcf3915dc01ad30" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_8134902075edc5e996ec0d71722" FOREIGN KEY ("owner_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "modify_liquidity_reccord" ADD CONSTRAINT "FK_430b2f79d98293631022471a10d" FOREIGN KEY ("pool_entity_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "modify_liquidity_reccord" ADD CONSTRAINT "FK_3b5836dd8b218113f7c7fb05274" FOREIGN KEY ("sender_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "swap_reccord" ADD CONSTRAINT "FK_1ee134afb92be9c3fc2b5fe9d65" FOREIGN KEY ("pool_entity_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "swap_reccord" ADD CONSTRAINT "FK_7a658a5896b4bca4b097a4d4565" FOREIGN KEY ("sender_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "donate_reccord" ADD CONSTRAINT "FK_292b419e04b723d968e150efc24" FOREIGN KEY ("pool_entity_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "donate_reccord" ADD CONSTRAINT "FK_1f36445a77d0839636ad31fd680" FOREIGN KEY ("sender_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "amm_configs"`)
        await db.query(`DROP TABLE "pool_manager"`)
        await db.query(`DROP TABLE "bundle"`)
        await db.query(`DROP TABLE "token_day_data"`)
        await db.query(`DROP INDEX "public"."IDX_b8950a8bc7b60231137573740e"`)
        await db.query(`DROP TABLE "token_hour_data"`)
        await db.query(`DROP INDEX "public"."IDX_7080974648c0d2c3baceb239c4"`)
        await db.query(`DROP TABLE "token"`)
        await db.query(`DROP TABLE "manager"`)
        await db.query(`DROP TABLE "hook"`)
        await db.query(`DROP TABLE "pool_day_data"`)
        await db.query(`DROP INDEX "public"."IDX_2f4c9e466537cf8101cbdceaea"`)
        await db.query(`DROP TABLE "pool_hour_data"`)
        await db.query(`DROP INDEX "public"."IDX_45e83e45011ed1000559b91726"`)
        await db.query(`DROP TABLE "pool"`)
        await db.query(`DROP INDEX "public"."IDX_338531367ed63e3eb8e1939980"`)
        await db.query(`DROP INDEX "public"."IDX_479321eabdd500587fddd0ee88"`)
        await db.query(`DROP INDEX "public"."IDX_0c748715160c52dcab5bb3492d"`)
        await db.query(`DROP TABLE "position"`)
        await db.query(`DROP INDEX "public"."IDX_f230b92ea5e4bdf8bd6658c629"`)
        await db.query(`DROP INDEX "public"."IDX_32d393d9b4c15d1f3253445453"`)
        await db.query(`DROP INDEX "public"."IDX_59d4badb979f73316f8e0a08a0"`)
        await db.query(`DROP INDEX "public"."IDX_128820371117dcf3915dc01ad3"`)
        await db.query(`DROP INDEX "public"."IDX_8134902075edc5e996ec0d7172"`)
        await db.query(`DROP TABLE "wallet"`)
        await db.query(`DROP TABLE "modify_liquidity_reccord"`)
        await db.query(`DROP INDEX "public"."IDX_430b2f79d98293631022471a10"`)
        await db.query(`DROP INDEX "public"."IDX_3b5836dd8b218113f7c7fb0527"`)
        await db.query(`DROP TABLE "swap_reccord"`)
        await db.query(`DROP INDEX "public"."IDX_1ee134afb92be9c3fc2b5fe9d6"`)
        await db.query(`DROP INDEX "public"."IDX_7a658a5896b4bca4b097a4d456"`)
        await db.query(`DROP TABLE "donate_reccord"`)
        await db.query(`DROP INDEX "public"."IDX_292b419e04b723d968e150efc2"`)
        await db.query(`DROP INDEX "public"."IDX_1f36445a77d0839636ad31fd68"`)
        await db.query(`DROP TABLE "pair_records"`)
        await db.query(`DROP INDEX "public"."IDX_748e6851d2065409a0b2d263ae"`)
        await db.query(`DROP INDEX "public"."IDX_82f0466ecec760560880a1e5a9"`)
        await db.query(`ALTER TABLE "token_day_data" DROP CONSTRAINT "FK_b8950a8bc7b60231137573740ea"`)
        await db.query(`ALTER TABLE "token_hour_data" DROP CONSTRAINT "FK_7080974648c0d2c3baceb239c4e"`)
        await db.query(`ALTER TABLE "pool_day_data" DROP CONSTRAINT "FK_2f4c9e466537cf8101cbdceaea1"`)
        await db.query(`ALTER TABLE "pool_hour_data" DROP CONSTRAINT "FK_45e83e45011ed1000559b91726f"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_338531367ed63e3eb8e1939980f"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_479321eabdd500587fddd0ee88b"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_0c748715160c52dcab5bb3492d6"`)
        await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_f230b92ea5e4bdf8bd6658c6292"`)
        await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_32d393d9b4c15d1f3253445453e"`)
        await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_59d4badb979f73316f8e0a08a02"`)
        await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_128820371117dcf3915dc01ad30"`)
        await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_8134902075edc5e996ec0d71722"`)
        await db.query(`ALTER TABLE "modify_liquidity_reccord" DROP CONSTRAINT "FK_430b2f79d98293631022471a10d"`)
        await db.query(`ALTER TABLE "modify_liquidity_reccord" DROP CONSTRAINT "FK_3b5836dd8b218113f7c7fb05274"`)
        await db.query(`ALTER TABLE "swap_reccord" DROP CONSTRAINT "FK_1ee134afb92be9c3fc2b5fe9d65"`)
        await db.query(`ALTER TABLE "swap_reccord" DROP CONSTRAINT "FK_7a658a5896b4bca4b097a4d4565"`)
        await db.query(`ALTER TABLE "donate_reccord" DROP CONSTRAINT "FK_292b419e04b723d968e150efc24"`)
        await db.query(`ALTER TABLE "donate_reccord" DROP CONSTRAINT "FK_1f36445a77d0839636ad31fd680"`)
    }
}
